[versions]
axi = "0.2.6"
kotlin = "2.1.20"
ktlint-gradle = "12.2.0"
ktlint-extras = "0.2.1"
dokka = "2.0.0"
coroutines = "1.10.1"
run-paper = "2.3.1"
shadow = "9.0.0-beta10"

[libraries]
plugin-kgp = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
plugin-axi = { module = "net.radsteve.axi:net.radsteve.axi.gradle.plugin", version.ref = "axi" }
plugin-ktlint = { module = "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlint-gradle" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
plugin-run-paper = { module = "xyz.jpenilla.run-paper:xyz.jpenilla.run-paper.gradle.plugin", version.ref = "run-paper" }
plugin-shadow = { module = "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin", version.ref = "shadow" }

ktlint-extras = { module = "net.radsteve.ktlint.extras:rules", version.ref = "ktlint-extras" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

axi-ksp = { module = "net.radsteve.axi:axi-ksp", version.ref = "axi" }
